# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e1a58b68ec60dd66faf9bdc1656083d586cbdd9bb9b64291827d3756d330b07f08f4a3f8f830cd65644f72c2f6ed2880450ca3eeaea92c18ade2d7affc3b09

test:
  secret_key_base: 8280b0221f5050d3369c5cd174815fadf4e76accffd48da60b918768c21728afff21f12745a01a93bd6827e371d284cde97f1553c9adcf7bc9d16f109186525d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
